Fix nightly and release yaml to actually work.
Signed-off-by: Johnathan Falk <johnathan.falk@gmail.com>

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -9,6 +9,8 @@ on:
     types: [created]
 
 permissions:
+  actions: write
+  attestations: write # Required for Sigstore Cosign
   contents: write
   packages: write
   id-token: write  # Required for Sigstore Cosign
@@ -20,7 +22,7 @@ jobs:
     strategy:
       matrix:
         goos: [linux, darwin]
-        goarch: [amd64, arm64]
+        arch: [amd64, arm64]
 
     steps:
       - name: Checkout Repository
@@ -62,17 +64,19 @@ jobs:
         run: go test -v ./...
 
       - name: Generate Code Coverage
-        run: go test -coverprofile=coverage.txt -covermode=atomic ./...
+        run: |
+            go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
+            go tool cover -html=./cover.out -o coverage.html
 
       - name: Build Binary
         run: |
           mkdir -p dist
-          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/webhook-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.run_id }} .
+          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.arch }} go build -o dist/webhook-${{ matrix.goos }}-${{ matrix.arch }}-${{ github.run_id }} .
 
       - name: Upload Binaries as Artifacts
         uses: actions/upload-artifact@v4
         with:
-          name: binaries-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.run_id }}
+          name: binaries-${{ matrix.goos }}-${{ matrix.arch }}-${{ github.run_id }}
           path: dist/
           if-no-files-found: ignore
 
@@ -85,6 +89,12 @@ jobs:
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
+
+      - uses: docker/login-action@v3.3.0
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Download Built Binaries
         uses: actions/download-artifact@v4
@@ -99,7 +109,7 @@ jobs:
       - name: Install Cosign
         uses: sigstore/cosign-installer@v3
         with:
-          cosign-release: "v2.0.1"
+          cosign-release: "v2.4.3"
 
       - name: Install Syft (for SBOM)
         run: |
@@ -121,24 +131,36 @@ jobs:
 
       - name: Sign Binaries with Cosign
         run: |
-          echo "${{ secrets.GITHUB_TOKEN }}" | cosign login ghcr.io --username $GITHUB_ACTOR --password-stdin
           for file in dist/*; do
-            cosign sign --yes $file
+            cosign sign-blob --yes --key env://COSIGN_PRIVATE_KEY $file
           done
+        env:
+          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
+          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
 
-      - name: Attest Binaries with Provenance
-        run: |
-          for file in dist/*; do
-            cosign attest --predicate provenance.json --type custom --yes $file
-          done
+      # - name: Attest Binaries with Provenance
+      #   run: |
+      #     for file in dist/*; do
+      #       cosign attest-blob --predicate provenance.json --type custom --yes --key env://COSIGN_PRIVATE_KEY $file
+      #     done
+      #   env:
+      #     COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
+      #     COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
 
       - name: Attest Binaries with SBOM
         run: |
-          echo "${{ secrets.GITHUB_TOKEN }}" | cosign login ghcr.io --username $GITHUB_ACTOR --password-stdin
           for sbom in sbom/*; do
             binary_name=$(basename $sbom .spdx.json)
-            cosign attest --predicate $sbom --type spdx --yes dist/$binary_name
+            cosign attest-blob --predicate $sbom --type spdx --yes --key env://COSIGN_PRIVATE_KEY dist/$binary_name
           done
+        env:
+          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
+          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
+
+      - name: Attest Build Provenance
+        uses: actions/attest-build-provenance@v2.2.0
+        with:
+          subject-path: 'dist/*'
 
 
   docker:
@@ -164,19 +186,19 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Log in to GitHub Container Registry (GHCR)
-        run: |
-          mkdir -p $(pwd)/kaniko/.docker
-          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
-          cp ~/.docker/config.json $(pwd)/kaniko/.docker/config.json
+      # - name: Log in to GitHub Container Registry (GHCR)
+      #   run: |
+      #     mkdir -p $(pwd)/kaniko/.docker
+      #     echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
+      #     cp ~/.docker/config.json $(pwd)/kaniko/.docker/config.json
 
-      - name: Validate Docker Login Configuration
-        run: |
-          if [ ! -f $(pwd)/kaniko/.docker/config.json ]; then
-            echo "❌ Docker config.json file is missing in $(pwd)/kaniko/.docker!"
-            exit 1
-          fi
-          echo "✅ Docker login validated. config.json is correctly placed in $(pwd)/kaniko/.docker."
+      # - name: Validate Docker Login Configuration
+      #   run: |
+      #     if [ ! -f $(pwd)/kaniko/.docker/config.json ]; then
+      #       echo "❌ Docker config.json file is missing in $(pwd)/kaniko/.docker!"
+      #       exit 1
+      #     fi
+      #     echo "✅ Docker login validated. config.json is correctly placed in $(pwd)/kaniko/.docker."
 
       - name: Download Built Binaries
         uses: actions/download-artifact@v4
@@ -185,23 +207,45 @@ jobs:
           merge-multiple: true
           path: dist/
 
-      - name: Build and Push Docker Image with Kaniko
-        run: |
-          export IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/ubuntu-autoinstall-webhook"
-          export ARCH="${{ matrix.arch }}"
-          export FULL_TAG="$IMAGE_NAME:latest-$ARCH"
+      - run: chmod +x dist/webhook-linux-${{ matrix.arch }}*
 
-          docker run --rm \
-            --privileged \
-            -v $(pwd)/kaniko/.docker:/kaniko/.docker \
-            -v "$(pwd)":/workspace \
-            -e DOCKER_CONFIG=/kaniko/.docker \
-            gcr.io/kaniko-project/executor:latest \
-            --context /workspace \
-            --dockerfile Dockerfile \
-            --custom-platform=linux/$ARCH \
-            --build-arg TARGETARCH=$ARCH \
-            --destination $FULL_TAG
+      - uses: int128/kaniko-action@v1.49.0
+        with:
+          executor: 'gcr.io/kaniko-project/executor:debug'
+          push: true
+          tags: |
+              ghcr.io/${{ github.repository_owner }}/ubuntu-autoinstall-webhook:${{ github.sha }}-${{ matrix.arch }}
+              ghcr.io/${{ github.repository_owner }}/ubuntu-autoinstall-webhook:latest-${{ github.sha }}-${{ matrix.arch }}
+              ghcr.io/${{ github.repository_owner }}/ubuntu-autoinstall-webhook:latest-${{ github.ref_name }}-${{ matrix.arch }}
+              ghcr.io/${{ github.repository_owner }}/ubuntu-autoinstall-webhook:latest-${{ matrix.arch }}
+              ${{ steps.metadata.outputs.tags }}
+          labels: ${{ steps.metadata.outputs.labels }}
+          cache: true
+          cache-repository: ghcr.io/${{ github.repository }}/cache
+          build-args: |
+            TARGETARCH=${{ matrix.arch }}
+          # file: Dockerfile
+          kaniko-args: |
+              --custom-platform=linux/${{ matrix.arch }}
+
+
+      # - name: Build and Push Docker Image with Kaniko
+      #   run: |
+      #     export IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/ubuntu-autoinstall-webhook"
+      #     export ARCH="${{ matrix.arch }}"
+      #     export FULL_TAG="$IMAGE_NAME:latest-$ARCH"
+
+      #     docker run --rm \
+      #       --privileged \
+      #       -v $(pwd)/kaniko/.docker:/kaniko/.docker \
+      #       -v "$(pwd)":/workspace \
+      #       -e DOCKER_CONFIG=/kaniko/.docker \
+      #       gcr.io/kaniko-project/executor:latest \
+      #       --context /workspace \
+      #       --dockerfile Dockerfile \
+      #       --custom-platform=linux/$ARCH \
+      #       --build-arg TARGETARCH=$ARCH \
+      #       --destination $FULL_TAG
 
   manifest:
     name: Create and Push Docker Manifest
@@ -219,19 +263,29 @@ jobs:
           export TAG="latest"
 
           docker manifest create $IMAGE_NAME:$TAG \
-            --amend $IMAGE_NAME:$TAG-amd64 \
-            --amend $IMAGE_NAME:$TAG-arm64
+            --amend $IMAGE_NAME:$TAG-${{ github.sha }}-amd64 \
+            --amend $IMAGE_NAME:$TAG-${{ github.sha }}-arm64
 
           docker manifest push $IMAGE_NAME:$TAG
 
+          docker manifest create $IMAGE_NAME:$TAG-${{ github.sha }} \
+            --amend $IMAGE_NAME:$TAG-${{ github.sha }}-amd64 \
+            --amend $IMAGE_NAME:$TAG-${{ github.sha }}-arm64
+
+          docker manifest push $IMAGE_NAME:$TAG-${{ github.sha }}
+
       - name: Install Cosign
         uses: sigstore/cosign-installer@v3
-        with:
-          cosign-release: "v2.0.1"
 
-      - name: Generate Attestation for Docker Image
+      - name: Generate Attestation for Release Docker Image
         run: |
-          export IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/ubuntu-autoinstall-webhook:latest"
-          export IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE_NAME)
           echo "${{ secrets.GITHUB_TOKEN }}" | cosign login ghcr.io --username $GITHUB_ACTOR --password-stdin
+          echo "attestation for amd64 image"
+          export IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/ubuntu-autoinstall-webhook:latest-${{ github.sha }}-amd64"
+          export IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE_NAME)
           cosign attest --predicate attestation.json --type spdx --yes $IMAGE_DIGEST
+          echo "attestation for arm64 image"
+          export IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/ubuntu-autoinstall-webhook:latest-${{ github.sha }}-arm64"
+          export IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE_NAME)
+          cosign attest --predicate attestation.json --type spdx --yes $IMAGE_DIGEST
+
